// Generated from the local HomDGCat and The Genius Archive snapshots.
window.HSR_CHARACTERS = [
  {
    "id": "special-yaoguang",
    "name": "爻光",
    "aliases": [
      "Yao Guang"
    ],
    "baseSpeed": 101,
    "icon": "./assets/genius-archive/Yao Guang.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false,
    "source": "The Genius Archive"
  },
  {
    "id": "special-silver999",
    "name": "银狼999",
    "aliases": [
      "银狼 LV.999",
      "Silver Wolf LV.999",
      "SW999"
    ],
    "baseSpeed": 110,
    "icon": "./assets/genius-archive/Silver Wolf LV.999.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false,
    "source": "The Genius Archive"
  },
  {
    "id": "special-huohua",
    "name": "火花",
    "aliases": [
      "Aha Sparkle"
    ],
    "baseSpeed": 107,
    "icon": "./assets/hsr-tool/1501.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Elation",
    "pathName": "欢愉",
    "rarity": 5,
    "ahaEligible": true,
    "source": "ahaSpeed snapshot"
  },
  {
    "id": "special-feiying",
    "name": "绯英",
    "aliases": [
      "Feiying"
    ],
    "baseSpeed": 104,
    "icon": "./assets/hsr-tool/1505.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Elation",
    "pathName": "欢愉",
    "rarity": 5,
    "ahaEligible": true,
    "source": "ahaSpeed snapshot"
  },
  {
    "id": "special-trailblazer-elation",
    "name": "欢愉主",
    "aliases": [
      "开拓者·欢愉",
      "欢愉开拓者",
      "雷主",
      "Trailblazer (Elation)"
    ],
    "baseSpeed": 106,
    "icon": "./assets/genius-archive/Trailblazer (Elation).png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Elation",
    "pathName": "欢愉",
    "rarity": 5,
    "ahaEligible": true,
    "source": "The Genius Archive"
  },
  {
    "id": "char-1221",
    "name": "云璃",
    "aliases": [],
    "baseSpeed": 94,
    "icon": "./assets/homdgcat/1221.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1321",
    "name": "大丽花",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1321.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1415",
    "name": "昔涟",
    "aliases": [],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1415.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-8007",
    "name": "记忆主",
    "aliases": [
      "开拓者",
      "开拓者·记忆",
      "冰主"
    ],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/8007.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1413",
    "name": "长夜月",
    "aliases": [],
    "baseSpeed": 99,
    "icon": "./assets/homdgcat/1413.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1414",
    "name": "丹恒 · 腾荒",
    "aliases": [],
    "baseSpeed": 97,
    "icon": "./assets/homdgcat/1414.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1410",
    "name": "海瑟音",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1410.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1412",
    "name": "刻律德菈",
    "aliases": [],
    "baseSpeed": 99,
    "icon": "./assets/homdgcat/1412.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1408",
    "name": "白厄",
    "aliases": [],
    "baseSpeed": 94,
    "icon": "./assets/homdgcat/1408.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1014",
    "name": "Saber",
    "aliases": [],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1014.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1015",
    "name": "Archer",
    "aliases": [],
    "baseSpeed": 105,
    "icon": "./assets/homdgcat/1015.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-2212",
    "name": "镜流",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1212.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-2205",
    "name": "刃",
    "aliases": [],
    "baseSpeed": 97,
    "icon": "./assets/homdgcat/1205.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-2005",
    "name": "卡芙卡",
    "aliases": [],
    "baseSpeed": 100,
    "icon": "./assets/homdgcat/1005.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-2006",
    "name": "银狼",
    "aliases": [],
    "baseSpeed": 107,
    "icon": "./assets/homdgcat/1006.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1406",
    "name": "赛飞儿",
    "aliases": [],
    "baseSpeed": 106,
    "icon": "./assets/homdgcat/1406.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1409",
    "name": "风堇",
    "aliases": [],
    "baseSpeed": 110,
    "icon": "./assets/homdgcat/1409.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1405",
    "name": "那刻夏",
    "aliases": [],
    "baseSpeed": 97,
    "icon": "./assets/homdgcat/1405.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1407",
    "name": "遐蝶",
    "aliases": [],
    "baseSpeed": 95,
    "icon": "./assets/homdgcat/1407.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1403",
    "name": "缇宝",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1403.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1404",
    "name": "万敌",
    "aliases": [],
    "baseSpeed": 95,
    "icon": "./assets/homdgcat/1404.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1401",
    "name": "大黑塔",
    "aliases": [],
    "baseSpeed": 99,
    "icon": "./assets/homdgcat/1401.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1402",
    "name": "阿格莱雅",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1402.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Remembrance",
    "pathName": "记忆",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1225",
    "name": "忘归人",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1225.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1313",
    "name": "星期日",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1313.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1317",
    "name": "乱破",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1317.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1220",
    "name": "飞霄",
    "aliases": [],
    "baseSpeed": 112,
    "icon": "./assets/homdgcat/1220.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1222",
    "name": "灵砂",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1222.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1223",
    "name": "貊泽",
    "aliases": [],
    "baseSpeed": 111,
    "icon": "./assets/homdgcat/1223.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1218",
    "name": "椒丘",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1218.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1224",
    "name": "三月七",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1224.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1310",
    "name": "流萤",
    "aliases": [],
    "baseSpeed": 104,
    "icon": "./assets/homdgcat/1310.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1314",
    "name": "翡翠",
    "aliases": [],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/1314.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1309",
    "name": "知更鸟",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1309.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1315",
    "name": "波提欧",
    "aliases": [],
    "baseSpeed": 107,
    "icon": "./assets/homdgcat/1315.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-8005",
    "name": "同谐主",
    "aliases": [
      "开拓者",
      "开拓者·同谐",
      "虚数主"
    ],
    "baseSpeed": 105,
    "icon": "./assets/homdgcat/8005.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1301",
    "name": "加拉赫",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1301.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1304",
    "name": "砂金",
    "aliases": [],
    "baseSpeed": 106,
    "icon": "./assets/homdgcat/1304.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1308",
    "name": "黄泉",
    "aliases": [],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1308.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1306",
    "name": "花火",
    "aliases": [
      "Sparkle"
    ],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1306.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1307",
    "name": "黑天鹅",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1307.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1312",
    "name": "米沙",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1312.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1214",
    "name": "雪衣",
    "aliases": [],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/1214.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1303",
    "name": "阮 · 梅",
    "aliases": [],
    "baseSpeed": 104,
    "icon": "./assets/homdgcat/1303.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1305",
    "name": "真理医生",
    "aliases": [],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/1305.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1215",
    "name": "寒鸦",
    "aliases": [],
    "baseSpeed": 110,
    "icon": "./assets/homdgcat/1215.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1217",
    "name": "藿藿",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1217.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1302",
    "name": "银枝",
    "aliases": [],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/1302.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1112",
    "name": "托帕&账账",
    "aliases": [],
    "baseSpeed": 110,
    "icon": "./assets/homdgcat/1112.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1210",
    "name": "桂乃芬",
    "aliases": [],
    "baseSpeed": 106,
    "icon": "./assets/homdgcat/1210.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1110",
    "name": "玲可",
    "aliases": [],
    "baseSpeed": 100,
    "icon": "./assets/homdgcat/1110.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1208",
    "name": "符玄",
    "aliases": [],
    "baseSpeed": 100,
    "icon": "./assets/homdgcat/1208.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1213",
    "name": "丹恒 · 饮月",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1213.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1111",
    "name": "卢卡",
    "aliases": [],
    "baseSpeed": 103,
    "icon": "./assets/homdgcat/1111.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1203",
    "name": "罗刹",
    "aliases": [],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1203.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1207",
    "name": "驭空",
    "aliases": [],
    "baseSpeed": 107,
    "icon": "./assets/homdgcat/1207.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1001",
    "name": "三月七",
    "aliases": [],
    "baseSpeed": 101,
    "icon": "./assets/homdgcat/1001.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1002",
    "name": "丹恒",
    "aliases": [],
    "baseSpeed": 110,
    "icon": "./assets/homdgcat/1002.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1003",
    "name": "姬子",
    "aliases": [],
    "baseSpeed": 96,
    "icon": "./assets/homdgcat/1003.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1004",
    "name": "瓦尔特",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1004.png",
    "element": "Imaginary",
    "elementName": "虚数",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1008",
    "name": "阿兰",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1008.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1009",
    "name": "艾丝妲",
    "aliases": [],
    "baseSpeed": 106,
    "icon": "./assets/homdgcat/1009.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1013",
    "name": "黑塔",
    "aliases": [],
    "baseSpeed": 100,
    "icon": "./assets/homdgcat/1013.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1101",
    "name": "布洛妮娅",
    "aliases": [],
    "baseSpeed": 99,
    "icon": "./assets/homdgcat/1101.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1102",
    "name": "希儿",
    "aliases": [],
    "baseSpeed": 115,
    "icon": "./assets/homdgcat/1102.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1103",
    "name": "希露瓦",
    "aliases": [],
    "baseSpeed": 104,
    "icon": "./assets/homdgcat/1103.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1104",
    "name": "杰帕德",
    "aliases": [],
    "baseSpeed": 92,
    "icon": "./assets/homdgcat/1104.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1105",
    "name": "娜塔莎",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1105.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1106",
    "name": "佩拉",
    "aliases": [],
    "baseSpeed": 105,
    "icon": "./assets/homdgcat/1106.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1107",
    "name": "克拉拉",
    "aliases": [],
    "baseSpeed": 90,
    "icon": "./assets/homdgcat/1107.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1108",
    "name": "桑博",
    "aliases": [],
    "baseSpeed": 102,
    "icon": "./assets/homdgcat/1108.png",
    "element": "Wind",
    "elementName": "风",
    "path": "Nihility",
    "pathName": "虚无",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1109",
    "name": "虎克",
    "aliases": [],
    "baseSpeed": 94,
    "icon": "./assets/homdgcat/1109.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1201",
    "name": "青雀",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1201.png",
    "element": "Quantum",
    "elementName": "量子",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1202",
    "name": "停云",
    "aliases": [],
    "baseSpeed": 112,
    "icon": "./assets/homdgcat/1202.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Harmony",
    "pathName": "同谐",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1204",
    "name": "景元",
    "aliases": [],
    "baseSpeed": 99,
    "icon": "./assets/homdgcat/1204.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Erudition",
    "pathName": "智识",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1206",
    "name": "素裳",
    "aliases": [],
    "baseSpeed": 107,
    "icon": "./assets/homdgcat/1206.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 4,
    "ahaEligible": false
  },
  {
    "id": "char-1209",
    "name": "彦卿",
    "aliases": [],
    "baseSpeed": 109,
    "icon": "./assets/homdgcat/1209.png",
    "element": "Ice",
    "elementName": "冰",
    "path": "Hunt",
    "pathName": "巡猎",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-1211",
    "name": "白露",
    "aliases": [],
    "baseSpeed": 98,
    "icon": "./assets/homdgcat/1211.png",
    "element": "Elec",
    "elementName": "雷",
    "path": "Abundance",
    "pathName": "丰饶",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-8001",
    "name": "毁灭主",
    "aliases": [
      "开拓者",
      "开拓者·毁灭",
      "物理主"
    ],
    "baseSpeed": 100,
    "icon": "./assets/homdgcat/8001.png",
    "element": "Phys",
    "elementName": "物理",
    "path": "Destruction",
    "pathName": "毁灭",
    "rarity": 5,
    "ahaEligible": false
  },
  {
    "id": "char-8003",
    "name": "存护主",
    "aliases": [
      "开拓者",
      "开拓者·存护",
      "火主"
    ],
    "baseSpeed": 95,
    "icon": "./assets/homdgcat/8003.png",
    "element": "Fire",
    "elementName": "火",
    "path": "Preservation",
    "pathName": "存护",
    "rarity": 5,
    "ahaEligible": false
  }
];


